name: splash_master_example
description: "Demonstrates how to use the splash_master plugin."
publish_to: 'none'

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  splash_master:
    path: ../
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/flutter_dash.png
    - assets/sample_lottie.json
    - assets/sample_video.mp4
    - assets/splash_image.png
    - assets/sample_splash_image.png
