name: splash_master
description: "Unifying Native and Flutter splash screens with multiple media options for a seamless user experience."
version: 0.0.1
homepage: https://github.com/SimformSolutionsPvtLtd/splash_master
issue_tracker: https://github.com/SimformSolutionsPvtLtd/splash_master/issues
topics:
  - splash-screen
  - flutter-splash-screen
  - flutter-splash
  - native-splash-screen
  - launch-screen

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.1.2
  video_player: ^2.9.1
  args: ^2.3.0
  xml: ^6.5.0
  yaml: ^3.1.2

dev_dependencies:
  flutter_lints: ^3.0.0

executables:
  splash_master: splash_master

scripts: scripts.yaml