name: splash_master
description: "Unifying Native and Flutter splash screens with multiple media options for a seamless user experience."
version: 1.0.0
repository: https://github.com/SimformSolutionsPvtLtd/splash_master
issue_tracker: https://github.com/SimformSolutionsPvtLtd/splash_master/issues
topics:
  - splash-screen
  - flutter-splash-screen
  - flutter-splash
  - native-splash-screen
  - launch-screen

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  xml: 6.6.1
  yaml: 3.1.3

dev_dependencies:
  flutter_lints: 3.0.0

executables:
  splash_master: splash_master

platforms:
  android:
  ios:

screenshots:
  - description: 'This screenshot showcases image as splash screen for ios.'
    path: preview/ios_image_splash.gif
  - description: 'This screenshot showcases image as splash screen for android.'
    path: preview/android_image_splash.gif
