name: splash_master
description: "Bridge the gap between native and flutter splash with splash master"
version: 0.0.1
homepage: https://github.com/SimformSolutionsPvtLtd/splash_screen

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.1.2

dev_dependencies:
  flutter_lints: ^3.0.0