import Cocoa
import FlutterMacOS

class MainFlutterWindow: NSWindow {

// BEGIN:SPLASH_MASTER_GENERATED
  // MARK: - Splash (generated by SplashMaster — do not edit between markers)

  private let _splashSize = NSSize(width: 800, height: 600)
  private let _mainSize   = NSSize(width: 800, height: 600)

  private var _splashContainer: NSView?

  override func awakeFromNib() {
    let flutterViewController = FlutterViewController()
    self.contentViewController = flutterViewController
    if let bgColor = NSColor(named: "SplashBackgroundColor") {
      flutterViewController.backgroundColor = bgColor
    }

    let screen = NSScreen.main ?? NSScreen.screens[0]
    let screenFrame = screen.visibleFrame
    let origin = NSPoint(
      x: screenFrame.midX - _splashSize.width / 2,
      y: screenFrame.midY - _splashSize.height / 2
    )
    self.setFrame(NSRect(origin: origin, size: _splashSize), display: true)

    _addSplashView()
    RegisterGeneratedPlugins(registry: flutterViewController)
    super.awakeFromNib()
  }

  private func _addSplashView() {
    guard let contentView = self.contentView else { return }

    let container = NSView(frame: contentView.bounds)
    container.autoresizingMask = [.width, .height]
    container.wantsLayer = true

    if let bgColor = NSColor(named: "SplashBackgroundColor") {
      container.layer?.backgroundColor = bgColor.cgColor
    }
    let imageView = NSImageView()
    imageView.image = NSImage(named: "SplashImage")
    imageView.translatesAutoresizingMaskIntoConstraints = false
          imageView.imageScaling = .scaleProportionallyUpOrDown
      imageView.setContentCompressionResistancePriority(.defaultLow, for: .horizontal)
      imageView.setContentCompressionResistancePriority(.defaultLow, for: .vertical)
    container.addSubview(imageView)



    NSLayoutConstraint.activate([
      imageView.centerXAnchor.constraint(equalTo: container.centerXAnchor),
      imageView.centerYAnchor.constraint(equalTo: container.centerYAnchor),
      imageView.widthAnchor.constraint(equalTo: container.widthAnchor),
      imageView.centerXAnchor.constraint(equalTo: container.centerXAnchor),
      imageView.centerYAnchor.constraint(equalTo: container.centerYAnchor),

    ])

    contentView.addSubview(container, positioned: .above, relativeTo: nil)
    _splashContainer = container
  }

  func removeSplash() {
    guard let splashView = _splashContainer else { return }
    NSAnimationContext.runAnimationGroup { context in
      context.duration = 0.3
      splashView.animator().alphaValue = 0
    } completionHandler: {
      splashView.removeFromSuperview()
      self._splashContainer = nil
    }

    if(_splashSize != _mainSize) {
      let screen = NSScreen.main ?? NSScreen.screens[0]
      let screenFrame = screen.visibleFrame
      let origin = NSPoint(
        x: screenFrame.midX - _mainSize.width / 2,
        y: screenFrame.midY - _mainSize.height / 2
      )
      self.setFrame(NSRect(origin: origin, size: _mainSize), display: true, animate: false)
    }
  }
// END:SPLASH_MASTER_GENERATED
}
